const DOCUMENT_TYPES = {
  QUOTATION: 'quotation',
  INVOICE: 'invoice',
};

const QUOTATION_STATUS = {
  DRAFT: 'Draft',
  SENT: 'Sent',
  VIEWED: 'Viewed',
  APPROVAL_PENDING: 'Approval Pending',
  APPROVED: 'Approved',
  ACCEPTED: 'Accepted',
  REJECTED: 'Rejected',
  EXPIRED: 'Expired',
};

const INVOICE_STATUS = {
  DRAFT: 'Draft',
  SENT: 'Sent',
  VIEWED: 'Viewed',
  PARTIALLY_PAID: 'Partially Paid',
  PAID: 'Paid',
  OVERDUE: 'Overdue',
  CANCELLED: 'Cancelled',
};

const QUOTATION_TRANSITIONS = {
  [QUOTATION_STATUS.DRAFT]: [QUOTATION_STATUS.SENT, QUOTATION_STATUS.EXPIRED],
  [QUOTATION_STATUS.SENT]: [
    QUOTATION_STATUS.VIEWED,
    QUOTATION_STATUS.APPROVAL_PENDING,
    QUOTATION_STATUS.ACCEPTED,
    QUOTATION_STATUS.REJECTED,
    QUOTATION_STATUS.EXPIRED,
  ],
  [QUOTATION_STATUS.VIEWED]: [
    QUOTATION_STATUS.APPROVAL_PENDING,
    QUOTATION_STATUS.ACCEPTED,
    QUOTATION_STATUS.REJECTED,
    QUOTATION_STATUS.EXPIRED,
  ],
  [QUOTATION_STATUS.APPROVAL_PENDING]: [QUOTATION_STATUS.APPROVED, QUOTATION_STATUS.REJECTED],
  [QUOTATION_STATUS.APPROVED]: [QUOTATION_STATUS.ACCEPTED, QUOTATION_STATUS.REJECTED, QUOTATION_STATUS.EXPIRED],
  [QUOTATION_STATUS.ACCEPTED]: [QUOTATION_STATUS.EXPIRED],
  [QUOTATION_STATUS.REJECTED]: [],
  [QUOTATION_STATUS.EXPIRED]: [],
};

const INVOICE_TRANSITIONS = {
  [INVOICE_STATUS.DRAFT]: [INVOICE_STATUS.SENT, INVOICE_STATUS.CANCELLED],
  [INVOICE_STATUS.SENT]: [INVOICE_STATUS.VIEWED, INVOICE_STATUS.PARTIALLY_PAID, INVOICE_STATUS.PAID, INVOICE_STATUS.OVERDUE, INVOICE_STATUS.CANCELLED],
  [INVOICE_STATUS.VIEWED]: [INVOICE_STATUS.PARTIALLY_PAID, INVOICE_STATUS.PAID, INVOICE_STATUS.OVERDUE, INVOICE_STATUS.CANCELLED],
  [INVOICE_STATUS.PARTIALLY_PAID]: [INVOICE_STATUS.PAID, INVOICE_STATUS.OVERDUE],
  [INVOICE_STATUS.OVERDUE]: [INVOICE_STATUS.PARTIALLY_PAID, INVOICE_STATUS.PAID],
  [INVOICE_STATUS.PAID]: [],
  [INVOICE_STATUS.CANCELLED]: [],
};

module.exports = {
  DOCUMENT_TYPES,
  QUOTATION_STATUS,
  INVOICE_STATUS,
  QUOTATION_TRANSITIONS,
  INVOICE_TRANSITIONS,
};
